version: '2'
services:
    jhipstersampleapplicationpostgres-app:
        image: jhipstersampleapplicationpostgres
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersampleapplicationpostgres-postgresql:5432/jhipsterSampleApplicationPostgres
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationpostgres-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersampleapplicationpostgres-postgresql
